### ISSUE TITLE
[TypeScript][Generator] Virtual Assistant Generator package is not updated with latest changes

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/botframework-solutions#29]
#### What project is affected?
`generator-botbuilder-assistant`

#### What language is this in?
`TypeScript`

#### What happens?
Following [Create a Virtual Assistant tutorial](https://microsoft.github.io/botframework-solutions/tutorials/typescript/create-assistant/1_intro/) leads to a build error.

#### What are the steps to reproduce this issue?
Follow the steps detailed in the [Create a Virtual Assistant tutorial](https://microsoft.github.io/botframework-solutions/tutorials/typescript/create-assistant/1_intro/) for TypeScript

At the step 3, [Create your assistant](https://microsoft.github.io/botframework-solutions/tutorials/typescript/create-assistant/3_create_project/), running the command `yo botbuilder-assistant` to create an assistant will result in two exceptions during the execution:
![image](https://user-images.githubusercontent.com/39467613/63542147-0c5e0d00-c4f6-11e9-89db-6837cbc53ad9.png)

#### What were you expecting to happen?
The command `yo botbuilder-assistant` should create an assistant without throwing any exception.

#### Any screenshots or additional context?
This seems to be an issue with the [Virtual Assistant Generator](https://www.npmjs.com/package/generator-botbuilder-assistant) not being updated with the latest changes.

The first exception shown, shows that the file [sample-assistant/src/index.ts](https://github.com/microsoft/botframework-solutions/blob/e0678f14156cff57d5139eb33c84b3552c5e00bc/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/index.ts#L144) it is using `skill.msAppId` instead of `skill.msaAppId`. This was updated in the [PR #1943](https://github.com/microsoft/botframework-solutions/pull/1943), almost a month ago.

The public generator is still using `msAppId`:
![image](https://user-images.githubusercontent.com/39467613/63544823-6235b380-c4fc-11e9-86b0-8c4b8043e0b2.png)

In the case of `MultiProviderAuthDialog`, the current version [takes two argument](https://github.com/microsoft/botframework-solutions/blob/e0678f14156cff57d5139eb33c84b3552c5e00bc/lib/typescript/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts#L30-L33). This change was introduced in the PR #1842 merged on July 13, just a little more than a month ago, however, the current public version was updated 2 months ago:
![image](https://user-images.githubusercontent.com/39467613/63542287-74acee80-c4f6-11e9-880c-cd84d49bb1b8.png)

To prove this, I checked the local files after install the Virtual Assistant Generator and it is still using a constructor with a single parameter.
![image](https://user-images.githubusercontent.com/39467613/63543495-5bf20800-c4f9-11e9-82ad-94e4fd8d1081.png)

As a temporary workaround, I built the latest version of `generator-botbuilder-assistant` from the [current master](https://github.com/microsoft/botframework-solutions), and replaced the one installed using the npm command.
Afterwards I ran again the command  `yo botbuilder-assistant`, and it completed without issues:
![image](https://user-images.githubusercontent.com/39467613/63544098-a7f17c80-c4fa-11e9-8a2c-c87d56776d8e.png)

**Comment by Batta32** [comment]
I think that this issue might be closed. Thoughts @dfavretto ?

**Comment by dfavretto** [comment]
@Batta32 a new version was published to MyGet, but I'd wait unti a stable release is published to `npmjs`.

**Comment by Batta32** [comment]
@dfavretto shall we close it now?

**Comment by dfavretto** [comment]
Sure, the latest stable version published to npmjs.org ([1.0.6](https://www.npmjs.com/package/generator-botbuilder-assistant)) implemented all the fixes. I'll close it.
