### ISSUE TITLE
[TypeScript] Migration to TypeScript 4.0

### ISSUE THREAD

**Issue by FedericoBernal** [southworks/botframework-solutions#441]
## User Story
As TypeScript v4 release was published
I want to update the solutions from botframework-solutions to TypeScript 4

## Acceptance Criteria 

Migrate the following solutions to TypeScript 4:

- [ ] [Virtual assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/samples/sample-assistant)
- [ ] [Skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/samples/sample-skill)
- [ ] [botskills](https://github.com/microsoft/botframework-solutions/tree/master/tools/botskills) 
- [ ] [Bot-solutions](https://github.com/microsoft/botframework-solutions/tree/master/sdk/typescript/libraries/bot-solutions).

## Resources

- Use [TypeScript 4.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html)

## Notes
_Appsettings.json updated_
![appsettings](https://user-images.githubusercontent.com/64086728/92643460-32e51680-f2b8-11ea-8c36-13fed35d84b2.png)

**Comment by Batta32** [comment]
I'll close this as it was promoted to MS
